# syntax=docker/dockerfile:1.4

FROM node:16-buster-slim as build

WORKDIR /frontend

ENV PATH /app/node_modules/.bin:$PATH

RUN npm install -g @angular/cli@15

COPY package.json /frontend/package.json
RUN npm i --force

COPY . /frontend

RUN ng build --configuration production --output-path=dist

FROM nginx:1.16.0-alpine

COPY --from=build /frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

