version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - common-net
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - common-net
  ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - '.:/src'
      - '/node_modules'
    networks:
      - common-net

networks:
  common-net: {}